### ISSUE TITLE
[Source]: AmoebaDB

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#133]
### Source Name

AmoebaDB

### Source URL

https://amoebadb.org/amoeba/app

### Source Description

AmoebaDB (http://AmoebaDB.org) is a new functional genomic databases serving the amoebozoa research communities, respectively. AmoebaDB contains the genomes of three Entamoeba species (E. dispar, E. invadens and E. histolityca) and microarray expression data for E. histolytica. The database belongs to the National Institute of Allergy and Infectious Diseases (NIAID) funded EuPathDB (http://EuPathDB.org) Bioinformatics Resource Center family of integrated databases and assume the same architectural and graphical design as other EuPathDB resources such as PlasmoDB and TriTrypDB. Importantly they utilize the graphical strategy builder that affords a database user the ability to ask complex multi-data-type questions with relative ease and versatility. Genomic scale data can be queried based on BLAST searches, annotation keywords and gene ID searches, GO terms, sequence motifs, protein characteristics, phylogenetic relationships and functional data such as transcript (microarray and EST evidence) and protein expression data. Search strategies can be saved within a user’s profile for future retrieval and may also be shared with other researchers using a unique strategy web address.

### Source Access

Unknown

### Source Funding

NIAID

### Source Relevance

NIAID high priority resource per: https://docs.google.com/spreadsheets/d/1qJT9MRoS6nGhWbPj2ao0A2YB1wKdzcSptU-1P1NtH9U/edit#gid=0&fvid=254061703

Note that this resource uses the same architecture as VEuPathDB so consider leveraging the VEuPathDB parser as a way to quick start this parser

### Related WBS task

- [X] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [ ] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [ ] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In process
- [ ] Blocked
- [ ] Will not include

### Source to-do list

- [X] License check- Can this source be included?
- [X] Class check- Does this source have the right class of research output for inclusions?
- [X] NIAID Review- Does NIAID approve of the inclusion of this source?
- [x] Data access check- Have data access issues been resolved?
- [x] Structured data check- Does this source have structured data?
- [ ] Mapping check- Has the properties from this source been mapped to the schema?
- [ ] Parser check- Has the parser been written?
- [ ] Parsed data check- Has a sanity check on the data obtained from this source been performed?
- [x] Merge data- Has the crawler/plugin been successfully integrated with the system?
- [ ] Issues could not be resolved - Add as a single record via the DDE

**Comment by gtsueng** [comment]
Note the data in this resource has already been integrated as part of VEuPathDB. 

To do: Determine if it is the NIAID team's intention to have a ResourceCatalog record of this data or to create a collection based on this data?

**Comment by gtsueng** [comment]
This resource will be added as a collection. I am closing this issue as it will be addressed by https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/135
