### ISSUE TITLE
[Source]: CryptoDB

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#134]
### Source Name

CryptoDB

### Source URL

https://cryptodb.org/cryptodb/app

### Source Description

The database, CryptoDB (http://CryptoDB.org), is a community bioinformatics resource for the AIDS-related apicomplexan-parasite, Cryptosporidium. CryptoDB integrates whole genome sequence and annotation with expressed sequence tag and genome survey sequence data and provides supplemental bioinformatics analyses and data-mining tools. A simple, yet comprehensive web interface is available for mining and visualizing the data. CryptoDB is allied with the databases PlasmoDB and ToxoDB via ApiDB, an NIH/NIAID-fundedBioinformatics Resource Center. Recent updates to CryptoDB include the deposition of annotated genome sequences for Cryptosporidium parvum and Cryptosporidium hominis, migration to a relational database (GUS), a new query and visualization interface and the introduction of Web services.

### Source Access

Unknown

### Source Funding

NIAID

### Source Relevance

A NIAID high priority resource according to https://docs.google.com/spreadsheets/d/1qJT9MRoS6nGhWbPj2ao0A2YB1wKdzcSptU-1P1NtH9U/edit#gid=0&fvid=254061703

Another DB leveraging the VEuPathDB architecture

### Related WBS task

- [X] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [ ] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [ ] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In process
- [ ] Blocked
- [ ] Will not include

### Source to-do list

- [X] License check- Can this source be included?
- [X] Class check- Does this source have the right class of research output for inclusions?
- [X] NIAID Review- Does NIAID approve of the inclusion of this source?
- [X] Data access check- Have data access issues been resolved?
- [X] Structured data check- Does this source have structured data?
- [ ] Mapping check- Has the properties from this source been mapped to the schema?
- [ ] Parser check- Has the parser been written?
- [ ] Parsed data check- Has a sanity check on the data obtained from this source been performed?
- [ ] Merge data- Has the crawler/plugin been successfully integrated with the system?
- [ ] Issues could not be resolved - Add as a single record via the DDE

**Comment by gtsueng** [comment]
These records will be included as collections. I am closing this issue as it will be addressed by https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/135
