### ISSUE TITLE
[Source]: Malaria Genomic Epidemiology Network (MalariaGEN)

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#137]
### Source Name

Malaria Genomic Epidemiology Network (MalariaGEN)

### Source URL

https://www.malariagen.net/

### Source Description

MalariaGEN is a global community of researchers using state-of-the-art tools and techniques to understand how genetic variation in humans, Plasmodium parasites, and Anopheles mosquitoes affects the transmission of malaria. We use this knowledge to develop more effective ways to control the disease.

### Short Description
MalariaGEN is an IID repository that includes multimodal data.

### Source Access

Yes, account needed

### Source Relevance

Identified as a high priority target by the NIAID team

### Related WBS task

- [ ] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [X] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [ ] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In process
- [ ] Blocked
- [ ] Will not include

### Source to-do list

- [X] License check- Can this source be included?
- [X] Class check- Does this source have the right class of research output for inclusions?
- [x] NIAID Review- Does NIAID approve of the inclusion of this source?
- [x] Data access check- Have data access issues been resolved?
- [x] Structured data check- Does this source have structured data?
- [x] Mapping check- Has the properties from this source been mapped to the schema?
- [x] Parser check- Has the parser been written?
- [x] Parsed data check- Has a sanity check on the data obtained from this source been performed?
- [x] Merge data- Has the crawler/plugin been successfully integrated with the system?
- [ ] Issues could not be resolved - Add as a single record via the DDE

**Comment by gtsueng** [comment]
The site has pages at the Data Package level which would be considered one Dataset record. I don't see any API, so we may have to crawl the site.

An example Data Package can be found here: https://www.malariagen.net/data_package/open-dataset-plasmodium-falciparum-v70/

Example mapping here: https://docs.google.com/presentation/d/1rbyYScpYYlHhD0tBZsczLyGqAFCPsVvgd8KyTG4BLqQ/edit#slide=id.p

**Comment by gtsueng** [comment]
This repository was discussed during the biweekly meeting dated 2024.04.30. Per the discussion, we will create a crawler for this resource.

**Comment by gtsueng** [comment]
@hartwickma @lisa-mml @rshabman @sudvenk

MalariaGen is now available on staging: https://data-staging.niaid.nih.gov/search?q=&filters=%28includedInDataCatalog.name%3A%28%22MalariaGEN%22%29%29

We are updating this issue to 'Review requested - staging'

**The ask:** Please review this new source on staging. If there are no issues with it, we seek approval to move it to production.

**Comment by hartwickma** [comment]
Approved, please move to production. Thank you.

**Comment by gtsueng** [comment]
Great! We will proceed to move this to Production.

**Comment by gtsueng** [comment]
This source is now on production. I am marking this issue as `pending close out` and will close it after a week if there are no more comments or concerns about this issue.
