### ISSUE TITLE
[Source]: Mass Spectrometry Interactive Virtual Environment (MassIVE)

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#139]
### Source Name

Mass Spectrometry Interactive Virtual Environment (MassIVE)

### Source URL

https://massive.ucsd.edu/ProteoSAFe/static/massive.jsp

API Documentation: https://ccms-ucsd.github.io/MassIVEDocumentation/#api/#massive-dataset-information

### Source Description

MassIVE is a community resource developed by the NIH-funded Center for Computational Mass Spectrometry to promote the global, free exchange of mass spectrometry data. MassIVE datasets can be assigned ProteomeXchange accessions to satisfy publication requirements. 

### Short Description
MassIVE is an NIH supported repository that includes mass spectrometry data.

### Source Access

No access issue, account not needed
Sample record: https://massive.ucsd.edu/ProteoSAFe/proxi/v0.1/datasets/MSV000094651

### Source Funding

NIH

### Source Relevance

NIAID high priority resource

### Related WBS task

- [ ] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [ ] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [X] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In process
- [ ] Blocked
- [ ] Will not include

### Source to-do list

- [X] License check- Can this source be included?
- [X] Class check- Does this source have the right class of research output for inclusions?
- [X] NIAID Review- Does NIAID approve of the inclusion of this source?
- [x] Data access check- Have data access issues been resolved?
- [x] Structured data check- Does this source have structured data?
- [x] Mapping check- Has the properties from this source been mapped to the schema?
- [x] Parser check- Has the parser been written?
- [x] Parsed data check- Has a sanity check on the data obtained from this source been performed?
- [x] Merge data- Has the crawler/plugin been successfully integrated with the system?
- [ ] Issues could not be resolved - Add as a single record via the DDE

**Comment by gtsueng** [comment]
MassIVE has a list of their public datasets here:
https://massive.ucsd.edu/ProteoSAFe/datasets.jsp#%7B%22query%22%3A%7B%7D%2C%22table_sort_history%22%3A%22createdMillis_dsc%22%7D

**Comment by gtsueng** [comment]
This repository was discussed during the biweekly meeting dated 2024.04.30. Per the discussion, we will create a crawler for this resource.

**Comment by gtsueng** [comment]
The mapping for this resource can be found here: https://docs.google.com/spreadsheets/d/115bj6yY7jOt3w_23SIcmRer1OijoD8wQDADcVpgC_wk/edit#gid=779139043

**Comment by gtsueng** [comment]
Per the discussion at the bi-weekly meeting dated 2024.06.25, moving forward, the NIAID team should be looped in on all communications with any repository including technical discussions.

For the record, @DylanWelzel please forward any email chains you received regarding your inquiries to MassIVE to NIAIDDataEcosystem@mail.nih.gov

**Comment by gtsueng** [comment]
@hartwickma @lisa-mml @rshabman @sudvenk

The parsing of doi and license information has been resolved in the build of MassIVE on Staging. The special character issue in authors affects ~75 records out of ~15K and must be resolved on MassIVE's end.

The Ask: Given the low percentage of records affected by the special character issue, we seek approval to add this repository to production.

**Comment by hartwickma** [comment]
Thank you @gtsueng for this update on the character issue with MassIVE. Please proceed to move to production. 

NIAID would like:

1. A timeline of when this issue is anticipated to be resolved and how the update will be incorporated in the production version of MassIVE
2. Please also include NIAID on communications with the repository (aspreviously discussed).

**Comment by gtsueng** [comment]
@hartwickma, 

@DylanWelzel will push MassIVE to production. He will also cc NIAIDDataEcosystem@mail.nih.gov in his follow-up inquiry/reply to MassIVE to see if they can provide a timeline as to when it will be resolved.

**Comment by gtsueng** [comment]
@hartwickma @rshabman @lisa-mml @sudvenk

MassIVE is now available on production. We have not heard back from the MassIVE team as to when they will fix the bad character encodings in their metadata.
