### ISSUE TITLE
[Source]: BioStudies ArrayExpress

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#140]
### Source Name

BioStudies ArrayExpress

### Source URL

https://www.ebi.ac.uk/biostudies/arrayexpress

### Source Description

The functional genomics data collection (ArrayExpress), stores data from high-throughput functional genomics experiments, and provides data for reuse to the research community. In line with community guidelines, a study typically contains metadata such as detailed sample annotations, protocols, processed data and raw data. Raw sequence reads from high-throughput sequencing studies are brokered to the European Nucleotide Archive (ENA), and links are provided to download the sequence reads from ENA. Data can be submitted to the ArrayExpress collection through its dedicated submission tool, Annotare.

### Short description
ArrayExpress is an NIH supported repository that includes high-throughput genomics data in the biomedical domain.

### Source Access

No access issue, account not needed

### Source Funding

EMBL

### Source Relevance

NIAID medium priority resource

### Related WBS task

- [ ] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [ ] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [X] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In process
- [ ] Blocked
- [ ] Will not include

### Source to-do list

- [X] License check- Can this source be included?
- [X] Class check- Does this source have the right class of research output for inclusions?
- [ ] NIAID Review- Does NIAID approve of the inclusion of this source?
- [X] Data access check- Have data access issues been resolved?
- [X] Structured data check- Does this source have structured data?
- [ ] Mapping check- Has the properties from this source been mapped to the schema?
- [ ] Parser check- Has the parser been written?
- [ ] Parsed data check- Has a sanity check on the data obtained from this source been performed?
- [ ] Merge data- Has the crawler/plugin been successfully integrated with the system?
- [ ] Issues could not be resolved - Add as a single record via the DDE

**Comment by gtsueng** [comment]
@DylanWelzel this repository has been evaluated as a medium-priority repository for integration. With your work on MassIVE and MalariaGEN, Jason's work on VEuPathDB collections, and my manual curation to create ResourceCatalogs, we've pretty much covered all of the high-priority resources, and can now start on the medium priority ones. 

Note that records from BioStudies-ArrayExpress may _potentially_ be aggregated by OMICs-DI, we should keep an eye out for duplication of records.
