### ISSUE TITLE
[Source]: High Priority Resource Catalogs

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#142]
### Source Name

NIAID High Priority Resource Catalogs

### Source URL

https://discovery.biothings.io/schema-playground

### Source Description

These are repositories that are high priority for integration, but currently are not of the right type for integration, so they will be added as ResourceCatalogs
- [x] https://dbaasp.org/home
- [x] https://www.ebi.ac.uk/emdb/
- [x] https://portal.hmpdacc.org/projects/t
- [x] https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/
- [x] http://www.peptideatlas.org/
- [x] https://www.uniprot.org/

### Source Access

Unknown

### Source Relevance

These are resources that were prioritized as high priority as of the end of April 2024

### Related WBS task

- [ ] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [ ] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [X] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In process
- [ ] Blocked
- [ ] Will not include

### Source to-do list

- [ ] License check- Can this source be included?
- [ ] Class check- Does this source have the right class of research output for inclusions?
- [X] NIAID Review- Does NIAID approve of the inclusion of this source?
- [ ] Data access check- Have data access issues been resolved?
- [ ] Structured data check- Does this source have structured data?
- [ ] Mapping check- Has the properties from this source been mapped to the schema?
- [ ] Parser check- Has the parser been written?
- [ ] Parsed data check- Has a sanity check on the data obtained from this source been performed?
- [ ] Merge data- Has the crawler/plugin been successfully integrated with the system?
- [X] Issues could not be resolved - Add as a single record via the DDE

**Comment by gtsueng** [comment]
As of 2024.05.14, The metadata for the following sources have been curated and are available [here](https://github.com/NIAID-Data-Ecosystem/nde-metadata-corrections/blob/main/metadata_for_DDE/resourceCatalogs/2024-05-14_batch_file.json). They will be uploaded once issues with the batch upload feature in the DDE have been addressed.
- https://dbaasp.org/home
- https://www.ebi.ac.uk/emdb/
- http://www.peptideatlas.org/
- https://www.uniprot.org/

The curation of metadata about the remaining two sources continues to be underway:
- https://portal.hmpdacc.org/projects/t
- https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/

**Comment by gtsueng** [comment]
As of 2024.05.21, The metadata for the following sources have been uploaded to the NIAID Data Ecosystem entry point in the DDE:
* https://dbaasp.org/home
* https://www.ebi.ac.uk/emdb/
* http://www.peptideatlas.org/
* https://www.uniprot.org/
* https://portal.hmpdacc.org/projects/t
* https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/

The records can be viewed in the DDE at: https://discovery.biothings.io/dataset?template=nde:resourcecatalog

These records will be viewable on staging once a new data build has been created

**Comment by gtsueng** [comment]
@hartwickma, @rshabman, @lisa-mml, @sudvenk

These sources are now on Staging. Upon receiving the "go-ahead", we will move them to Production.

**Comment by gtsueng** [comment]
@DylanWelzel @jal347 These DDE-ingested resources have been approved for Production. The list of resources approved for production vs staging has been updated.

**Comment by gtsueng** [comment]
@hartwickma, @rshabman, @lisa-mml, @sudvenk as seen during the biweekly call dated 2024.06.25, these high priority resources are now on production.

I am changing the status of this issue to 'pending close out' and will close the issue after a week if there are no additional comments or concerns

**Comment by gtsueng** [comment]
Based on discussions initiated during the bi-weekly meeting dated 2024.06.25, the `genre` and `abstract` field for each ResourceCatalog may need to be updated such that any non-IID resources are categorized as `generalist`

**Comment by gtsueng** [comment]
The `genre` field for these Resource Catalogs have been updated. I am marking this issue as `pending close out` and will close this issue after a week if there are no additional comments or changes to be made.

**Comment by rshabman** [comment]
Hi @gtsueng, @hartwickma, @rshabman, @lisa-mml, @sudvenk: Can the Scripps team evaluate PaVE? The Papillomavirus Episteme – under the direction of Dr. Alison McBride is a curated repository of annotated papillomavirus genomes.  It also has a toolset for analysis of user-submitted genomes.  https://pave.niaid.nih.gov/.  Ideally we can integrate at the dataset level, if not, can you please map out an approach to bring online as a resource catalog for a shorter term solution? If this is already in a GH issue, apologies for cross posting.

**Comment by EmilyHaag** [comment]
An issue has been created for PaVE: https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/226
