### ISSUE TITLE
[Source]: NIAID Medium priority Resource Catalogs (part 1)

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#144]
### Source Name

NIAID Medium priority Resource Catalogs (part 1)

### Source URL

https://discovery.biothings.io/guide/nde/ResourceCatalog

### Source Description

This is a list of resources prioritized for inclusion by NIAID into the NIAID Data Ecosystem that have been sorted by the Scripps team for inclusion as Resource Catalogs:
- [x] https://flybase.org/ (2024-05-23)
- [x] https://wormbase.org//#012-34-5 (2024-05-23)
- [x] https://yeastgenome.org/ (2024-05-23)
- [x] https://www.ncbi.nlm.nih.gov/clinvar/intro/ (2024-06-14)
- [x] https://www.clinicalgenome.org/ (2024-06-18)
- [x] https://www.beiresources.org/ (2024-06-18)
- [x] http://www.specimenrepository.org/RepositorySite/home.html (2024-07-23)
- [x] https://aledb.org/ (2024-07-23)
- [x] https://bacdive.dsmz.de/ (2024-07-23)
- [x] https://ecocyc.org/ (2024-07-31)
- [x] https://hfv.lanl.gov/content/index (2024-07-31)
- [x] https://hcv.lanl.gov/content/index (2024-07-31)
- [x] https://www.hiv.lanl.gov/content/index (2024-07-31)

Note that there are more prioritized resources, but they will be added to a separate issue. Not all the resources been prioritized nor have all the prioritized resources been evaluated for inclusion as Resource Catalogs.

### Source Access

Unknown

### Source Relevance

These are resources that have been prioritized NIAID for inclusion

### Related WBS task

- [X] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [X] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [X] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [X] In process
- [ ] Blocked
- [ ] Will not include

### Source to-do list

- [ ] License check- Can this source be included?
- [ ] Class check- Does this source have the right class of research output for inclusions?
- [X] NIAID Review- Does NIAID approve of the inclusion of this source?
- [ ] Data access check- Have data access issues been resolved?
- [ ] Structured data check- Does this source have structured data?
- [ ] Mapping check- Has the properties from this source been mapped to the schema?
- [ ] Parser check- Has the parser been written?
- [ ] Parsed data check- Has a sanity check on the data obtained from this source been performed?
- [ ] Merge data- Has the crawler/plugin been successfully integrated with the system?
- [X] Issues could not be resolved - Add as a single record via the DDE

**Comment by gtsueng** [comment]
As of 2024.06.18, the following ResourceCatalogs have been ingested into the DDE:
* https://flybase.org/ (https://discovery.biothings.io/dataset/136f77a47a3e203a)
* https://wormbase.org//#012-34-5 (https://discovery.biothings.io/dataset/5a6bc368148ab46e)
* https://yeastgenome.org/ (https://discovery.biothings.io/dataset/56d15748b50a6e70)
* https://www.ncbi.nlm.nih.gov/clinvar/intro/ (https://discovery.biothings.io/dataset/a13ce89d9fe6c6c4)
* https://www.clinicalgenome.org/ (https://discovery.biothings.io/dataset/b880e7dc2c2437e0)

**Comment by gtsueng** [comment]
As of 2024.06.21, the following ResourceCatalogs have been ingested into the DDE:
https://www.beiresources.org/ (https://discovery.biothings.io/dataset/933c129858283201)

**Comment by gtsueng** [comment]
As of 2024.07.23, the following ResourceCatalogs have been ingested into the DDE:
http://www.specimenrepository.org/RepositorySite/home.html | https://discovery.biothings.io/dataset/eb4e1ad280483af0
https://aledb.org/ | https://discovery.biothings.io/dataset/11bb8ccc46a23eb7
https://bacdive.dsmz.de/ | https://discovery.biothings.io/dataset/e9c5ccfa4872afe2

**Comment by gtsueng** [comment]
As of 2024.07.31, the following Resource Catalogs have been ingested into the DDE:
Hemorrhagic Fever Viruses (HFV) Database Project | https://discovery.biothings.io/dataset/c28d2988769e7528
Hepatitis C Virus Database Project (HCV) | https://discovery.biothings.io/dataset/1f4b344365159fa5
HIV Databases | https://discovery.biothings.io/dataset/692ee0c5c7bc9166

**Comment by gtsueng** [comment]
@hartwickma, @lisa-mml, @rshabman, @sudvenk

The Ask: Please review the following ResourceCatalogs in Staging and check the box if they are approved for Production. 

 - [ ] [https://flybase.org/](https://data-staging.niaid.nih.gov/resources?id=dde_136f77a47a3e203a)
 - [ ] [https://wormbase.org//#012-34-5](https://data-staging.niaid.nih.gov/resources?id=dde_5a6bc368148ab46e)
 - [ ] [https://yeastgenome.org/](https://data-staging.niaid.nih.gov/resources?id=dde_56d15748b50a6e70)
 - [ ] [https://www.ncbi.nlm.nih.gov/clinvar/intro/](https://data-staging.niaid.nih.gov/resources?id=dde_a13ce89d9fe6c6c4)
 - [ ] [https://www.clinicalgenome.org/](https://data-staging.niaid.nih.gov/resources?id=dde_b880e7dc2c2437e0)
 - [ ] [https://www.beiresources.org/](https://data-staging.niaid.nih.gov/resources?id=dde_933c129858283201)
 - [ ] [http://www.specimenrepository.org/RepositorySite/home.html](https://data-staging.niaid.nih.gov/resources?id=dde_eb4e1ad280483af0)
 - [ ] [https://aledb.org/](https://data-staging.niaid.nih.gov/resources?id=dde_11bb8ccc46a23eb7)
 - [ ] [https://bacdive.dsmz.de/](https://data-staging.niaid.nih.gov/resources?id=dde_e9c5ccfa4872afe2)
 - [ ] [https://ecocyc.org/](https://data-staging.niaid.nih.gov/resources?id=dde_814769360e4ce207)
 - [ ] [https://hfv.lanl.gov/content/index](https://data-staging.niaid.nih.gov/resources?id=dde_c28d2988769e7528)
 - [ ] [https://hcv.lanl.gov/content/index](https://data-staging.niaid.nih.gov/resources?id=dde_1f4b344365159fa5)
 - [ ] [https://www.hiv.lanl.gov/content/index](https://data-staging.niaid.nih.gov/resources?id=dde_692ee0c5c7bc9166)

**Comment by gtsueng** [comment]
Thanks, @hartwickma! We will move the resource catalogs in this issue to production EXCEPT for flybase, wormbase, and yeastgenome (SGD). We will add those 3 to the [The medium priority catalogs part 2](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/issues/166) to be revisited in the future and mark this issue as `pending close out`
