### ISSUE TITLE
[Parser Fix]: BD2K LINCS DCIC changes requested by NIAID team

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#146]
### Issue Name

BD2K LINCS DCIC changes requested by NIAID team

### Issue Description

The NIAID team has requested the following fixes for BD2K-LINCS-DCIC:
- [x] Please change the name of this repository to ‘LINCS’. The data that is accessed through the Ecosystem Portal is from the LINCS Data Portal, so ‘LINCS’ is more accurate then ‘BD2K-LINCS DCIC’ (which refers to the Data Coordination and Integration Center of the larger BD2K initiative) : 
![image](https://github.com/NIAID-Data-Ecosystem/nde-crawlers/assets/9200138/4adc58e1-b96f-4b6b-9b6c-b82db606dcbe)

### Related WBS task

- [ ] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [ ] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [X] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

**Comment by gtsueng** [comment]
@hartwickma, @lisa-mml, @rshabman, @sudvenk

The requested name change for LINCS has been implemented on staging and production. We are marking this issue as `pending close out` and will close it after a week if there are no more concerns/comments regarding this issue.
