### ISSUE TITLE
[Source]: NIAID Medium priority Resource Catalogs (part 2)

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#166]
### Source Name

NIAID Medium priority Resource Catalogs (part 2)

### Source URL

https://discovery.biothings.io/guide/nde/ResourceCatalog

### Source Description

This is a list of resources prioritized for inclusion by NIAID into the NIAID Data Ecosystem that have been sorted by the Scripps team for inclusion as Resource Catalogs:

- [x] [https://flybase.org/](https://data-staging.niaid.nih.gov/resources?id=dde_136f77a47a3e203a) (2024.05.23)
- [x] [https://wormbase.org//#012-34-5](https://data-staging.niaid.nih.gov/resources?id=dde_5a6bc368148ab46e) (2024.05.23)
- [x] [https://yeastgenome.org/](https://data-staging.niaid.nih.gov/resources?id=dde_56d15748b50a6e70) (2024.05.23)
- [x] [https://pave.niaid.nih.gov/](https://data-staging.niaid.nih.gov/resources?id=dde_194d74d04e1ae30e) (2025.01.30)
- [x] [https://www.iddo.org/](https://data-staging.niaid.nih.gov/resources?id=dde_db7f0ed9441f9bed) (2025.01.30)
- [x] [https://www.iddo.org/wwarn](https://data-staging.niaid.nih.gov/resources?id=dde_0fa5ab6e627f4e6e) (2025.01.30)
- [x] https://www.immgen.org/ (on staging as of 2025.03.25)
- [x] https://mycocosm.jgi.doe.gov/Aspnid1/Aspnid1.home.html (on staging as of 2025.03.25)
- [x] https://www.hvtn.org/ (on staging as of 2025.03.25)
- [x] https://bioinformatics.niaid.nih.gov/chemokinedb/ (ingested via Figshare)
- [x] https://www.ceirr-network.org/ (uploaded to the DDE on 2025.04.18)
- [x] https://chemdb.niaid.nih.gov/ (uploaded to the DDE on 2025.04.18)
- [x] http://networks.systemsbiology.net/mtb/ (uploaded to the DDE on 2025.04.25)
- [x] PaxDB: dde_173df65ab56bb219 (uploaded to the DDE on 2025.05.14)
- [x] N3C: dde_373d5e89c734f65e (uploaded to the DDE on 2025.05.14) 

### Source Access

Unknown

### Source Relevance

These are resources that have been prioritized NIAID for inclusion

### Related WBS task

- [X] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [X] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [X] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In process
- [ ] Blocked
- [ ] Will not include

### Source to-do list

- [ ] License check- Can this source be included?
- [ ] Class check- Does this source have the right class of research output for inclusions?
- [ ] NIAID Review- Does NIAID approve of the inclusion of this source?
- [ ] Data access check- Have data access issues been resolved?
- [ ] Structured data check- Does this source have structured data?
- [ ] Mapping check- Has the properties from this source been mapped to the schema?
- [ ] Parser check- Has the parser been written?
- [ ] Parsed data check- Has a sanity check on the data obtained from this source been performed?
- [ ] Merge data- Has the crawler/plugin been successfully integrated with the system?
- [X] Issues could not be resolved - Add as a single record via the DDE

**Comment by gtsueng** [comment]
Moved the following from #144 to this issue for later discussion:
-[x] [https://flybase.org/](https://data-staging.niaid.nih.gov/resources?id=dde_136f77a47a3e203a) (2024.05.23)
-[x] [https://wormbase.org//#012-34-5](https://data-staging.niaid.nih.gov/resources?id=dde_5a6bc368148ab46e) (2024.05.23)
-[x] [https://yeastgenome.org/](https://data-staging.niaid.nih.gov/resources?id=dde_56d15748b50a6e70) (2024.05.23)

**Comment by gtsueng** [comment]
The following resources are on Staging as of 2025.01.30
* [https://pave.niaid.nih.gov/](https://data-staging.niaid.nih.gov/resources?id=dde_194d74d04e1ae30e) (2024.01.30)
* [https://www.iddo.org/](https://data-staging.niaid.nih.gov/resources?id=dde_db7f0ed9441f9bed) (2024.01.30)
* [https://www.iddo.org/wwarn](https://data-staging.niaid.nih.gov/resources?id=dde_0fa5ab6e627f4e6e) (2024.01.30)

**Comment by gtsueng** [comment]
The following resources are on Production as of 2025.03.07

    [https://pave.niaid.nih.gov/](https://data-staging.niaid.nih.gov/resources?id=dde_194d74d04e1ae30e) (2024.01.30)
    [https://www.iddo.org/](https://data-staging.niaid.nih.gov/resources?id=dde_db7f0ed9441f9bed) (2024.01.30)
    [https://www.iddo.org/wwarn](https://data-staging.niaid.nih.gov/resources?id=dde_0fa5ab6e627f4e6e) (2024.01.30)

**Comment by gtsueng** [comment]
The following resources are on Staging as of 2025.03.25
* https://www.immgen.org/ (on staging as of 2025.03.25)
* https://mycocosm.jgi.doe.gov/Aspnid1/Aspnid1.home.html (on staging as of 2025.03.25)
* https://www.hvtn.org/ (on staging as of 2025.03.25)

**Comment by gtsueng** [comment]
The following resources have been uploaded to the DDE as of 2025.04.18

[Centers of Excellence for Influenza Research and Response (CEIRR)](https://discovery.biothings.io/resource/5a908221f16d72c6)
[ChemDB HIV, Opportunistic Infection and Tuberculosis Therapeutics Database](https://discovery.biothings.io/resource/9082657ce16ad050)

**Comment by EmilyHaag** [comment]
These Resource Catalog integration reports have all been created/updated in the Google drive: https://drive.google.com/drive/folders/11gvCo5e4BGYznovvQxXm_rD2g_PCIxLN?usp=drive_link

**Comment by gtsueng** [comment]
The following resource catalogs were added to the DDE on 2025.05.14:
* PaxDB: dde_173df65ab56bb219 (uploaded to the DDE on 2025.05.14)
* N3C: dde_373d5e89c734f65e (uploaded to the DDE on 2025.05.14)

**Comment by gtsueng** [comment]
@hartwickma, @rshabman, @lisa-mml, @sudvenk

We seek approval to move the following ResourceCatalogs to Production
- [ ] https://flybase.org/ [(on staging as of 2024.05.23)](https://data-staging.niaid.nih.gov/resources?id=dde_136f77a47a3e203a)
- [ ] https://wormbase.org//#012-34-5 [(on staging as of 2024.05.23)](https://data-staging.niaid.nih.gov/resources?id=dde_5a6bc368148ab46e)
- [ ] https://yeastgenome.org/ [(on staging as of 2024.05.23)](https://data-staging.niaid.nih.gov/resources?id=dde_56d15748b50a6e70)
- [ ] https://mycocosm.jgi.doe.gov/Aspnid1/Aspnid1.home.html [(on staging as of 2025.03.25)](https://data-staging.niaid.nih.gov/resources?id=dde_e2cff654d63ac34b)
- [ ] https://www.hvtn.org/ [(on staging as of 2025.03.25)](https://data-staging.niaid.nih.gov/resources?id=dde_cca1b70e988160b4)
- [ ] https://www.ceirr-network.org/ [(on staging as of 2025.04.30)](https://data-staging.niaid.nih.gov/resources?id=dde_5a908221f16d72c6)
- [ ] https://chemdb.niaid.nih.gov/ [(on staging as of 2025.04.30)](https://data-staging.niaid.nih.gov/resources?id=dde_9082657ce16ad050)
- [ ] http://networks.systemsbiology.net/mtb/ [(on staging as of 2025.04.30)](https://data-staging.niaid.nih.gov/resources?id=dde_ff62b2285250ec8a)
- [ ] https://pax-db.org/ [(on staging as of 2025.05.30)](https://data-staging.niaid.nih.gov/resources?id=dde_173df65ab56bb219)
- [ ] https://covid.cd2h.org/ [(on staging as of 2025.05.30)](https://data-staging.niaid.nih.gov/resources?id=dde_373d5e89c734f65e)

**Comment by darya-pokutnaya** [comment]
Hi @gtsueng. Thank you for integrating all of these repositories at the ResourceCatalog level. Two key points:

1. Moving forward, the Integration Reports should clearly state why an API was not used, when one was available. Please note, we also observed this in the Project Tycho Integration Report, and will be making the same request in the Project Tycho GH issue. Please start a separate GitHub issue to discuss repositories with APIs that were not ingested using the API. We have noted this on several occasions, and a quick call to discuss APIs would be beneficial. Please let us know your prepared to discuss!

We identified these 3 resources that have APIs but were determined to not be ingestible at the dataset level via the API: 

- https://flybase.github.io/api/swagger-ui/
- https://wormbase.org/about/userguide/for_developers#3--10
- https://yeastgenome.org/api/doc

2. Several of the items on the list (e.g., HVTN & CEIRR) are already Program Collections. The ResourceCatalogs that you created here are not pointing the resources produced by the Program Collections. Rather, they are pointing to the Program's home page. We would like the ResourceCatalogs to point to unique content, such as the resource itself, so that it is not duplicative of the Program Collection content.

-Please hold off on moving the ResourceCatalog for HVTN to Production or if you are able to find the repository, please link it and let us know.
-Please link the CEIRR ResourceCatalog to the CEIRR Reagants page (https://www.ceirr-network.org/resources/reagents). Once it is linked, it can be moved to Production.

We approve the following ResourceCatalogs to be moved to Production: 
- https://flybase.org/ [(on staging as of 2024.05.23)](https://data-staging.niaid.nih.gov/resources?id=dde_136f77a47a3e203a)
- https://wormbase.org//#012-34-5 [(on staging as of 2024.05.23)](https://data-staging.niaid.nih.gov/resources?id=dde_5a6bc368148ab46e)
- https://yeastgenome.org/ [(on staging as of 2024.05.23)](https://data-staging.niaid.nih.gov/resources?id=dde_56d15748b50a6e70)
- https://mycocosm.jgi.doe.gov/Aspnid1/Aspnid1.home.html [(on staging as of 2025.03.25)](https://data-staging.niaid.nih.gov/resources?id=dde_e2cff654d63ac34b)
- https://chemdb.niaid.nih.gov/ [(on staging as of 2025.04.30)](https://data-staging.niaid.nih.gov/resources?id=dde_9082657ce16ad050)
- http://networks.systemsbiology.net/mtb/ [(on staging as of 2025.04.30)](https://data-staging.niaid.nih.gov/resources?id=dde_ff62b2285250ec8a)
- https://pax-db.org/ [(on staging as of 2025.05.30)](https://data-staging.niaid.nih.gov/resources?id=dde_173df65ab56bb219)
- https://covid.cd2h.org/ [(on staging as of 2025.05.30)](https://data-staging.niaid.nih.gov/resources?id=dde_373d5e89c734f65e)

Many thanks and let us know if you need any further clarification on any of these points!
