### ISSUE TITLE
[Parser Fix]: OMICS-DI literature supplemental data

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#170]
### Issue Name

OMICS-DI literature supplemental data

### Issue Description

OMICS-DI ingests publication records for supplemental data from Biostudies-literature (which ingests from European PMC). Clicking 'access data' for these records from the Discovery Portal will take you to the OMICS-DI record, which when clicked, may take you to the Biostudies record, which when clicked, will take you to the European PMC record where you may (or may not) find the downloadable supplemental files. 

These records for publication supplemental data make up about ~1.4M out of ~2.2M OMICS-DI records.

To be determined: Do we want to continue to ingest and include all of OMICS-DI, or do we want to filter OMICS-DI such that only data that is not supplemental data from publications is included?
* Pros of ingesting as is: 
  * PMC Supplemental data is too messy to ingest. The supplemental data ingested via Biostudies into OMICS-DI is presumably a curated subset, where the metadata has been aligned with OMICS-DI and is expected to be within the scope of OMICS-DI
  * Helps users find OMICS data that would be otherwise buried in the literature or only in OMICS-DI
  * Keeps OMICS-DI intact
* Cons of ingesting as is: 
  * Adds a large number of records where data access is very convoluted (need to follow 2-3 links to get to it, if it's even available).
  * Can easily be mistaken as publication records instead of dataset records since the metadata for the supplemental data is based the publication record
  * It can potentially make OMICS-DI faster to parse and update if such records were skipped based on a base url or identifier match

To do:
- [ ] Determine if the literature supplemental data ingested into OMICS-DI should be included
- [ ] IF it should NOT be included, update the parser to skip anything with a `biostudies-literature` in the url

### Issue Example

https://data.niaid.nih.gov/resources?id=s-epmc6182170

### Related WBS task

- [ ] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [ ] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [X] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

**Comment by gtsueng** [comment]
Note the decision made on this issue will affect the number of records that will be linked via NCBI LinkOut (see issue https://github.com/NIAID-Data-Ecosystem/niaid-feedback/issues/126)

**Comment by rshabman** [comment]
@gtsueng a common point of feedback is that the portal returns don't take a user to the actual data.  I suspect this is because many returns are OmicsDI and the majority of these link to the supplemental publication link.  Therefore my **preliminary** recommendation is that the publication supplemental NOT be included and update the parser to skip anything with a biostudies-literature in the url.  However, this would me 1M+ records would be removed from NCBI LinkOut and potentially remove traffic to the site - is this correct?  Can you confirm I understand the issue correctly before we make a final decision?

**Comment by gtsueng** [comment]
@rshabman Yes, that is exactly the issue. OMICS-DI supplemental publications "datasets" will be records that definitely have a link to a citation. These citations can be leveraged to potentially direct traffic from the PubMed record to the NIAID Data Ecosystem via NCBI LinkOut. But, as you pointed out, the user may or may not get to the actual data since the path from OMICS-DI to the supplemental data can be convoluted.

**Comment by rshabman** [comment]
Thanks @gtsueng. @hartwickma and I discussed, please update the parser to skip anything with a biostudies-literature in the url. While this may cut down on traffic, we want folks coming to the portal to find data easily.

**Comment by rshabman** [comment]
Please proceed with the BioLink registration (other GitHub issue) and retain OMICS DI in it's current form.  We don't want to reduce the number of CREID records at this point.  If I understand correctly, we can always change the OMICS DI ingest at a later date.

**Comment by gtsueng** [comment]
Got it! Thanks, @rshabman

**Comment by andrewsu** [comment]
For reference, here are links to the 22 records in the CREID program collection that we would lose by eliminating the biostudies-literature subset of omicsDI:

| NDE link  | BioStudies link |
| ------------- | ------------- |
| https://data.niaid.nih.gov/resources?id=s-epmc6703872 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc6703872 |
| https://data.niaid.nih.gov/resources?id=s-epmc6853903 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc6853903 |
| https://data.niaid.nih.gov/resources?id=s-epmc6906250 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc6906250 |
| https://data.niaid.nih.gov/resources?id=s-epmc6955268 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc6955268 |
| https://data.niaid.nih.gov/resources?id=s-epmc7213566 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7213566 |
| https://data.niaid.nih.gov/resources?id=s-epmc7250850 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7250850 |
| https://data.niaid.nih.gov/resources?id=s-epmc7263506 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7263506 |
| https://data.niaid.nih.gov/resources?id=s-epmc7286545 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7286545 |
| https://data.niaid.nih.gov/resources?id=s-epmc7332453 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7332453 |
| https://data.niaid.nih.gov/resources?id=s-epmc7354470 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7354470 |
| https://data.niaid.nih.gov/resources?id=s-epmc7359519 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7359519 |
| https://data.niaid.nih.gov/resources?id=s-epmc7391951 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7391951 |
| https://data.niaid.nih.gov/resources?id=s-epmc7597632 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7597632 |
| https://data.niaid.nih.gov/resources?id=s-epmc7604506 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7604506 |
| https://data.niaid.nih.gov/resources?id=s-epmc7648063 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7648063 |
| https://data.niaid.nih.gov/resources?id=s-epmc7680145 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7680145 |
| https://data.niaid.nih.gov/resources?id=s-epmc7839664 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7839664 |
| https://data.niaid.nih.gov/resources?id=s-epmc7846801 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7846801 |
| https://data.niaid.nih.gov/resources?id=s-epmc7860990 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7860990 |
| https://data.niaid.nih.gov/resources?id=s-epmc7872373 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7872373 |
| https://data.niaid.nih.gov/resources?id=s-epmc7880427 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7880427 |
| https://data.niaid.nih.gov/resources?id=s-epmc7881699 | https://www.ebi.ac.uk/biostudies/europepmc/studies/s-epmc7881699 |

It appears from [Mary Hannah Currin's email](https://github.com/NIAID-Data-Ecosystem/niaid-feedback/issues/157#issue-2564994414) that these records were identified based on a search of NDE and not some independent index of CREID datasets.  Also, after spot checking a few of these records, they generally aren't what I'd consider a "dataset" personally...

**Comment by rshabman** [comment]
Thanks @andrewsu.  I didn't realize these records were not independently indexed by CREID.  @gtsueng the CREID data was the only reason we decided to keep the OmicsDI biostudies.  With this update we recommend to update the parser to skip anything with a biostudies-literature in the url.  Apologies for the change in direction, and hope this adjustment isn't too disruptive.

**Comment by gtsueng** [comment]
@jal347 will remove the biostudies-literature-ingested from OMICS-DI

**Comment by gtsueng** [comment]
These records have been manually removed from the Production API. A re-run of the data is in progress to ensure up-to-date, more accurate removal of the records. I am marking this issue as `Pending close out`.
