### ISSUE TITLE
[Source]: VirulenceFinder

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#221]
### Source Name

VirulenceFinder

### Source URL

https://cge.food.dtu.dk/services/VirulenceFinder/

### Source Description

Identifcation of acquired virulence genes. 

citation:
1. Joensen KG, Scheutz F, Lund O, Hasman H, Kaas RS, Nielsen EM, Aarestrup FM. (2014) Real-time whole-genome sequencing for routine typing, surveillance, and outbreak detection of verotoxigenic Escherichia coli. J. Clin. Micobiol. 52(5) 1501-1510.
View the abstract [here](http://www.ncbi.nlm.nih.gov/pubmed/24574290).

isBasedOn:
2. Malberg Tetzschner AM, Johnson JR, Johnston BD, Lund O, Scheutz F. (2020) In Silico Genotyping of Escherichia coli Isolates for Extraintestinal Virulence Genes by Use of Whole-Genome Sequencing Data. J. Clin. Micobiol. 58(10) e01269-20. doi:10.1128/JCM.01269-20.
View the abstract [here](https://jcm.asm.org/content/58/10/e01269-20).

2. Clausen PTLC, Aarestrup FM, Lund O. (2018). 3. Rapid and precise alignment of raw reads against redundant databases with KMA. BMC Bioinformatics 19(1):307.
View the abstract [here](https://pubmed.ncbi.nlm.nih.gov/30157759/).

3. Camacho C, Coulouris G, Avagyan V, Ma N, Papadopoulos J, Bealer K, Madden TL. (2009). 4. BLAST+: architecture and applications. BMC Bioinformatics 10(1):421.
View the abstract [here](https://pubmed.ncbi.nlm.nih.gov/20003500/).

### Source Access

No access issue, account not needed

### Source Funding

Part of the https://www.genomicepidemiology.org/ site

### Source Relevance

Seems like a tool with potential value to the IID community

### Related WBS task

- [ ] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [ ] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [ ] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In process
- [ ] Blocked
- [ ] Will not include

### Source to-do list

- [ ] License check- Can this source be included?
- [ ] Class check- Does this source have the right class of research output for inclusions?
- [ ] NIAID Review- Does NIAID approve of the inclusion of this source?
- [ ] Data access check- Have data access issues been resolved?
- [ ] Structured data check- Does this source have structured data?
- [ ] Mapping check- Has the properties from this source been mapped to the schema?
- [ ] Parser check- Has the parser been written?
- [ ] Parsed data check- Has a sanity check on the data obtained from this source been performed?
- [ ] Merge data- Has the crawler/plugin been successfully integrated with the system?
- [ ] Issues could not be resolved - Add as a single record via the DDE
