### ISSUE TITLE
[Parser Fix]: Assign `conditionsOfAccess`: `closed` or `restricted`

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#222]
### Issue Name

Assign `conditionsOfAccess`: `closed`

### Issue Description

The following repositories require registration in order to be able to access the data-- Update the parsers for these repositories such that the `conditionsOfAccess` field are set to `closed` and that the `isAccessibleForFree` field is set to `true` 
* VEuPathDB and all of VEuPathDB collection items
  * ![image](https://github.com/user-attachments/assets/99c02777-3602-4b82-b1e4-bf351c101895)
* ImmPort
  * ![image](https://github.com/user-attachments/assets/fb6c639e-742a-4b28-9e0e-34a63383dc97)

The following repositories have restrictions on the data access and use (outside of the don't do anything unethical/illegal that ImmPort has) -- Update the parsers for these repositories such that the `conditionsOfAccess` field are set to `restricted` and that the `isAccessibleForFree` field is set to `true`
* Vivli
  * ![image](https://github.com/user-attachments/assets/786beaae-6a2e-4524-820b-95402e07d599)
* ReframeDB
  * ![image](https://github.com/user-attachments/assets/42ca7acc-00e8-4621-be36-13ce7d5cb1a2)
 

### Related WBS task

- [X] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [X] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [X] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [ ] In progress
- [ ] Blocked
- [ ] Will not address

**Comment by gtsueng** [comment]
I am marking this issue as `pending close out` as it has been addressed
