### ISSUE TITLE
[Parser Fix]: Verify ingest of `about` field, or update DDE parser if `about` field not ingested

### ISSUE THREAD

**Issue by gtsueng** [NIAID-Data-Ecosystem/nde-crawlers#223]
### Issue Name

Verify ingest of `about` field, or update DDE parser if `about` field not ingested

### Issue Description

We have added a new property, `about` to the NDE ResourceCatalog schema. This property captures the data types that are available for a resource.

This field is currently only found in the ResourceCatalog type

To do:
- [x] Check if the current parser will ingest/parse the `about` field
  - [x] Update the parser to ingest/parse the `about` field, if it does not do so
- [x] Update the ES mapping to include the `about` field
- [x] Update the data build for the DDE
- [x] Ensure the updated data is available on all 3 APIs 

### Issue Example

https://github.com/NIAID-Data-Ecosystem/nde-metadata-corrections/blob/1505fc9d9b2c2b0d5f43aa3618b4f1f1c0d5a3bd/metadata_for_DDE/resourceCatalogs/ACTG.json#L278

### Related WBS task

- [X] Check here if this repository is funded by NIAID (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/11)
- [X] Check here if this repository only has IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)
- [X] Check here if this is a generalist repository with IID data (https://github.com/NIAID-Data-Ecosystem/nde-roadmap/issues/12)

### For internal use only. Assignee, please select the status of this issue

- [ ] Not yet started
- [x] In progress
- [ ] Blocked
- [ ] Will not address

**Comment by DylanWelzel** [comment]
Add `about.displayName` with correct spacing from `about.name`

Mapping for PascalCase names:
```
    "MolecularSequence" --> "Molecular Sequence"
    "ClinicalStudy" --> "Clinical Study"
    "MedicalCondition" --> "Medical Condition"
    "ProteinSet"--> "Protein set"
    "SpectralLibrary" --> "Spectral Library"
    "MolecularEntity" --> "Molecular Entity"
    "GeneVariant" --> "Gene Variant"
    "ChemicalSubstance" --> "Chemical Substance"
    "BioSample" --> "Biosample"
    "GeneSet" --> "Gene Set"
    "SampleSet" --> "Sample Set"
```

Current unique about.name values in our data 01-08-2024:
```
[
    "Image",
    "Protein",
    "Software",
    "Publication",
    "Patient",
    "Experiment",
    "Pathway",
    "Dataset",
    "MolecularSequence",
    "Genome",
    "Gene",
    "ClinicalStudy",
    "MedicalCondition",
    "Phenotype",
    "Peptide",
    "ProteinSet",
    "SpectralLibrary",
    "Sample",
    "Taxon",
    "MolecularEntity",
    "GeneVariant",
    "Epitope",
    "ChemicalSubstance"
  ]
```

**Comment by gtsueng** [comment]
I am marking this issue as 'pending close out'
